# Alcatraz Preset Source: git+https://github.com/bolasblack/alcatraz.git#9f948d7498766b9a9dcff1ac2d0919ead4bf2cd5:.alca.nmem.toml
#:schema https://raw.githubusercontent.com/bolasblack/alcatraz/refs/heads/master/alca-config.schema.json

mounts = [
  "${HOME}/ai-now:/root/ai-now",
]

[envs]
NMEM_API_URL = "http://host.docker.internal:14242"

[network]
lan-access = [
  '${alca:HOST_IP}:14242',
]